# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# This software was developed and implemented by MDSight, LLC
# with project management by Lieberthal & Associates, LLC
# and funding from the Casualty Actuarial Society.

from __future__ import annotations

from datetime import datetime
import logging
import json
import re
from io import BytesIO
from pathlib import Path
from typing import Dict, List, Tuple

from fpdf import FPDF

BACKEND_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = BACKEND_DIR.parent.parent

logger = logging.getLogger(__name__)

DOCUMENT_ROOTS = [
    {
        'id': 'input',
        'label': 'Input Documents',
        'description': 'Source files supplied to the pipeline.',
        'base_path': PROJECT_ROOT / 'input'
    },
    {
        'id': 'output',
        'label': 'Pipeline Output',
        'description': 'Artifacts generated by each processing step.',
        'base_path': PROJECT_ROOT / 'output'
    }
]

DIRECTORY_DESCRIPTIONS = {
    'fhir_bundles': 'FHIR bundles awaiting or undergoing processing.',
    'text_data': 'Raw text transcripts and supplemental materials.',
    'example': 'Sample input data for demonstrations.',
    '1_data-process_fhir_bundle': 'Step 1 output: structured claim bundle generated from FHIR.',
    '2_data-add_documents': 'Step 2 output: claim bundle enriched with extra documents.',
    '3_process-combine_text_to_json': 'Step 3 output: combined text converted to JSON encounters.'
}

SUPPORTED_PDF_EXTENSIONS = {'.json', '.txt', '.md', '.markdown', '.yaml', '.yml'}
MAX_LIST_ITEMS = 8
MAX_STRING_LENGTH = 3000
MAX_BLOCKS = 1200
ACRONYM_MAP = {
    'fhir': 'FHIR',
    'llm': 'LLM',
    'pdf': 'PDF',
    'json': 'JSON',
    'api': 'API',
    'ehr': 'EHR'
}


def _human_readable_size(num: float, suffix: str = 'B') -> str:
    for unit in ['', 'K', 'M', 'G', 'T', 'P']:
        if abs(num) < 1024.0:
            return f"{num:3.1f}{unit}{suffix}"
        num /= 1024.0
    return f"{num:.1f}E{suffix}"


def _prettify_label(name: str) -> str:
    if not name:
        return ''
    normalized = re.sub(r'[_\-\s]+', ' ', str(name)).strip()
    if not normalized:
        return ''
    tokens = []
    for token in normalized.split():
        key = token.lower()
        if key in ACRONYM_MAP:
            tokens.append(ACRONYM_MAP[key])
        elif token.isdigit():
            tokens.append(token)
        elif len(token) <= 4 and token.isupper():
            tokens.append(token)
        else:
            tokens.append(token.capitalize())
    formatted = ' '.join(tokens)
    match = re.match(r'^(\d+)\s+(.*)', formatted)
    if match:
        return f"Step {match.group(1)}: {match.group(2)}"
    return formatted


def _clean_markdown_text(text) -> str:
    if text is None:
        return ''
    if not isinstance(text, str):
        text = str(text)

    text = text.replace('\r\n', '\n').replace('\r', '\n')
    lines: List[str] = []
    for raw_line in text.split('\n'):
        line = raw_line.rstrip()
        if not line.strip():
            lines.append('')
            continue

        heading_match = re.match(r'^(#{1,6})\s+(.*)', line)
        if heading_match:
            heading_text = heading_match.group(2).strip()
            lines.append(heading_text.upper())
            continue

        bullet_match = re.match(r'^[-*+]\s+(.*)', line)
        if bullet_match:
            bullet_text = bullet_match.group(1).strip()
            lines.append(f"- {bullet_text}")
            continue

        cleaned = re.sub(r'(\*\*|__)(.*?)\1', r'\2', line)
        cleaned = re.sub(r'`([^`]+)`', r'\1', cleaned)
        cleaned = re.sub(r'\*(.*?)\*', r'\1', cleaned)
        lines.append(cleaned)

    return '\n'.join(lines)


def _clean_text_value(value) -> str:
    if value is None:
        return 'N/A'
    if isinstance(value, bool):
        return 'Yes' if value else 'No'
    if isinstance(value, (int, float)):
        return str(value)

    text = _clean_markdown_text(value)
    if len(text) > MAX_STRING_LENGTH:
        return text[:MAX_STRING_LENGTH - 3] + '...'
    return text


def _soft_wrap_long_tokens(text: str, limit: int = 60) -> str:
    """Insert soft breaks into long tokens so FPDF can render them."""
    if not text or len(text) <= limit:
        return text

    parts: List[str] = []
    # Split while preserving whitespace
    for segment in re.split(r'(\s+)', text):
        if not segment:
            continue
        if segment.isspace() or len(segment) <= limit:
            parts.append(segment)
            continue
        logger.debug("Soft wrapping long token (len=%d) for PDF output", len(segment))
        # Special handling for URLs - try to break at slashes
        if '://' in segment or segment.startswith('/'):
            url_parts = re.split(r'(/)', segment)
            for part in url_parts:
                if len(part) <= limit:
                    parts.append(part)
                else:
                    # Still too long, break it up
                    for idx in range(0, len(part), limit):
                        parts.append(part[idx:idx + limit])
        else:
            # Regular long token, break at limit
            for idx in range(0, len(segment), limit):
                parts.append(segment[idx:idx + limit])
    return ''.join(parts)


def _pdf_safe_text(text) -> str:
    if text is None:
        return ''
    if not isinstance(text, str):
        text = str(text)
    wrapped = _soft_wrap_long_tokens(text)
    return wrapped.encode('latin-1', 'replace').decode('latin-1')


def _split_into_paragraphs(text: str) -> List[str]:
    if text is None:
        return []
    text = text.replace('\r\n', '\n').replace('\r', '\n')
    blocks: List[str] = []
    for chunk in text.split('\n\n'):
        trimmed = chunk.strip()
        if not trimmed:
            continue
        lines = [line.strip() for line in trimmed.split('\n')]
        blocks.append('\n'.join(lines))
    return blocks if blocks else [text.strip()]


def _build_content_blocks(value, depth: int = 0, label: str | None = None,
                          blocks: List[Dict] | None = None,
                          context: Dict | None = None) -> List[Dict]:
    if blocks is None:
        blocks = []
    if context is None:
        context = {'count': 0, 'truncated': False}
    if context.get('truncated'):
        return blocks

    def add_block(block: Dict):
        if context.get('truncated'):
            return
        if context['count'] >= MAX_BLOCKS:
            if not context.get('truncated'):
                context['truncated'] = True
                logger.warning(
                    "Truncating PDF content after %d blocks while processing label %s",
                    context['count'],
                    label
                )
                blocks.append({
                    'type': 'paragraph',
                    'depth': depth,
                    'text': '... Additional content truncated for brevity ...'
                })
            return
        blocks.append(block)
        context['count'] += 1

    if isinstance(value, dict):
        if label:
            add_block({'type': 'heading', 'depth': depth, 'text': label})
        for key, val in value.items():
            _build_content_blocks(val, depth + 1, _prettify_label(key), blocks, context)
    elif isinstance(value, list):
        if label:
            add_block({'type': 'heading', 'depth': depth, 'text': label})
        label_root = None
        if label:
            label_root = label[:-1] if label.endswith('s') and len(label) > 1 else label
        for idx, item in enumerate(value[:MAX_LIST_ITEMS]):
            item_label = f"{label_root or 'Item'} {idx + 1}"
            _build_content_blocks(item, depth + 1, item_label, blocks, context)
        if len(value) > MAX_LIST_ITEMS:
            add_block({
                'type': 'paragraph',
                'depth': depth + 1,
                'text': f"... {len(value) - MAX_LIST_ITEMS} additional items not shown ..."
            })
    else:
        text = _clean_text_value(value)
        if label:
            if '\n' in text or len(text) > 160:
                add_block({'type': 'heading', 'depth': depth, 'text': label})
                add_block({'type': 'paragraph', 'depth': depth + 1, 'text': text})
            else:
                add_block({'type': 'label_value', 'depth': depth, 'label': label, 'text': text})
        else:
            add_block({'type': 'paragraph', 'depth': depth, 'text': text})
    return blocks


def _create_file_metadata(file_path: Path) -> Dict:
    try:
        stat_info = file_path.stat()
        relative_path = file_path.relative_to(PROJECT_ROOT)
        extension = file_path.suffix.lower()
        return {
            'name': file_path.name,
            'path': str(relative_path),
            'size_bytes': stat_info.st_size,
            'size_human': _human_readable_size(stat_info.st_size),
            'modified': datetime.fromtimestamp(stat_info.st_mtime).isoformat(),
            'extension': extension,
            'pdf_available': extension in SUPPORTED_PDF_EXTENSIONS
        }
    except Exception as exc:
        return {
            'name': file_path.name,
            'path': str(file_path),
            'error': str(exc),
            'pdf_available': False
        }


def _collect_directory_files(directory_path: Path) -> List[Dict]:
    files: List[Dict] = []
    if not directory_path.exists() or not directory_path.is_dir():
        logger.debug("Skipping non-directory path during collection: %s", directory_path)
        return files
    for item in directory_path.iterdir():
        if item.is_file():
            files.append(_create_file_metadata(item))
        else:
            logger.debug("Ignoring nested directory %s inside %s", item, directory_path)
    files.sort(key=lambda f: f.get('modified', ''), reverse=True)
    return files


def list_document_groups() -> List[Dict]:
    logger.debug("Listing document groups for %d configured roots", len(DOCUMENT_ROOTS))
    groups = []
    for root in DOCUMENT_ROOTS:
        base_path = root['base_path']
        directories = []
        if base_path.exists():
            for item in sorted(base_path.iterdir()):
                if item.name.startswith('.'):
                    logger.debug("Skipping hidden path: %s", item)
                    continue
                if item.is_dir():
                    files = _collect_directory_files(item)
                    directories.append({
                        'id': str(item.relative_to(PROJECT_ROOT)),
                        'label': _prettify_label(item.name),
                        'description': DIRECTORY_DESCRIPTIONS.get(item.name, ''),
                        'path': str(item.relative_to(PROJECT_ROOT)),
                        'type': 'directory',
                        'file_count': len(files),
                        'files': files
                    })
                elif item.is_file():
                    files = [_create_file_metadata(item)]
                    directories.append({
                        'id': str(item.relative_to(PROJECT_ROOT)),
                        'label': _prettify_label(item.name),
                        'description': DIRECTORY_DESCRIPTIONS.get(item.name, ''),
                        'path': str(item.relative_to(PROJECT_ROOT)),
                        'type': 'file',
                        'file_count': 1,
                        'files': files
                    })
                else:
                    logger.debug("Ignoring unexpected filesystem entry: %s", item)
        else:
            logger.warning("Document root does not exist: %s", base_path)
        directories.sort(key=lambda d: d['label'])
        groups.append({
            'id': root['id'],
            'label': root['label'],
            'description': root.get('description', ''),
            'base_path': str(base_path.relative_to(PROJECT_ROOT)),
            'directories': directories
        })
        logger.debug(
            "Collected %d directories for root %s",
            len(directories),
            base_path
        )
    return groups


def _get_allowed_document_bases() -> List[Path]:
    bases = []
    for root in DOCUMENT_ROOTS:
        try:
            bases.append(root['base_path'].resolve())
        except FileNotFoundError:
            bases.append((PROJECT_ROOT / root['base_path']).resolve())
    return bases


def resolve_document_path(relative_path: str) -> Path:
    if not relative_path:
        raise ValueError('Missing path parameter')
    logger.debug("Resolving document path for %s", relative_path)
    candidate = (PROJECT_ROOT / relative_path).resolve()
    for base in _get_allowed_document_bases():
        try:
            candidate.relative_to(base)
            logger.debug("Resolved path %s within base %s", candidate, base)
            return candidate
        except ValueError:
            continue
    raise ValueError('Requested file is outside of allowed document directories')


def _render_block_to_pdf(pdf: FPDF, block: Dict):
    depth = block.get('depth', 0)
    # Reduce max indentation to prevent horizontal space issues
    indent = min(depth, 4) * 3
    base_x = pdf.l_margin + indent
    block_type = block.get('type')

    # Calculate available width explicitly
    # Page width minus margins minus current indentation
    page_width = pdf.w
    available_width = page_width - base_x - pdf.r_margin
    min_width_mm = 40  # Minimum 40mm for readable content

    # If not enough space, reduce indentation
    if available_width < min_width_mm:
        indent = max(0, indent - 6)
        base_x = pdf.l_margin + indent
        available_width = page_width - base_x - pdf.r_margin

    # Scale font size for deeply nested content
    if depth > 3:
        base_font_size = 9
        heading_font_size = max(11 - depth, 9)
    else:
        base_font_size = 10
        heading_font_size = max(12 - depth, 10)

    try:
        if block_type == 'heading':
            pdf.set_font('Helvetica', 'B', heading_font_size)
            pdf.set_x(base_x)
            pdf.multi_cell(available_width, 7, _pdf_safe_text(block.get('text', '')))
            pdf.ln(1)
        elif block_type == 'label_value':
            pdf.set_x(base_x)
            pdf.set_font('Helvetica', 'B', base_font_size)
            pdf.multi_cell(available_width, 6, _pdf_safe_text(f"{block.get('label', '')}:"))
            pdf.set_font('Helvetica', '', base_font_size)
            for paragraph in _split_into_paragraphs(block.get('text', '')):
                label_indent = 4 if available_width > 50 else 2
                pdf.set_x(base_x + label_indent)
                value_width = max(available_width - label_indent, min_width_mm)
                pdf.multi_cell(value_width, 5, _pdf_safe_text(paragraph))
            pdf.ln(1)
        elif block_type == 'paragraph':
            pdf.set_font('Helvetica', '', base_font_size)
            for paragraph in _split_into_paragraphs(block.get('text', '')):
                pdf.set_x(base_x)
                pdf.multi_cell(available_width, 5, _pdf_safe_text(paragraph))
            pdf.ln(1)
    except Exception as exc:
        # Fallback rendering if multi_cell fails
        logger.warning("Failed to render block at depth %d: %s. Using fallback.", depth, exc)
        try:
            pdf.set_font('Helvetica', '', 9)
            pdf.set_x(pdf.l_margin)
            fallback_width = page_width - pdf.l_margin - pdf.r_margin
            text = block.get('text', '') or block.get('label', '')
            pdf.multi_cell(fallback_width, 5, _pdf_safe_text(str(text)[:200]))
            pdf.ln(1)
        except Exception as fallback_exc:
            logger.error("Fallback rendering also failed: %s", fallback_exc)


def _build_pdf_buffer(file_path: Path) -> BytesIO:
    logger.debug("Building PDF buffer for %s", file_path)
    suffix = file_path.suffix.lower()
    if suffix not in SUPPORTED_PDF_EXTENSIONS:
        raise ValueError('PDF export is not supported for this file type')

    if suffix == '.json':
        try:
            with open(file_path, 'r', encoding='utf-8') as json_file:
                data = json.load(json_file)
            blocks = _build_content_blocks(data)
        except Exception as exc:
            logger.exception("Failed to parse JSON for PDF conversion: %s", file_path)
            fallback_text = (
                f"Unable to parse JSON file: {exc}\n\nRaw content:\n\n"
                f"{file_path.read_text(encoding='utf-8', errors='ignore')}"
            )
            blocks = [{'type': 'paragraph', 'depth': 0, 'text': fallback_text}]
    else:
        text_content = file_path.read_text(encoding='utf-8', errors='ignore')
        cleaned = _clean_markdown_text(text_content)
        blocks = [{'type': 'paragraph', 'depth': 0, 'text': cleaned}]

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Calculate full page width for header
    content_width = pdf.w - pdf.l_margin - pdf.r_margin

    # Render title
    try:
        pdf.set_font('Helvetica', 'B', 16)
        title_text = _pdf_safe_text(_prettify_label(file_path.stem) or file_path.name)
        pdf.multi_cell(content_width, 10, title_text)
        pdf.ln(2)
    except Exception as exc:
        logger.error("Failed to render PDF title: %s", exc)
        # Try with simpler text
        pdf.set_font('Helvetica', 'B', 14)
        pdf.multi_cell(content_width, 10, _pdf_safe_text(file_path.name[:100]))
        pdf.ln(2)

    try:
        stat_info = file_path.stat()
        metadata_lines = [
            f"Source path: {file_path.relative_to(PROJECT_ROOT)}",
            f"Last updated: {datetime.fromtimestamp(stat_info.st_mtime).strftime('%Y-%m-%d %H:%M:%S')}",
            f"Original size: {_human_readable_size(stat_info.st_size)}"
        ]
    except FileNotFoundError:
        metadata_lines = []

    if metadata_lines:
        try:
            pdf.set_font('Helvetica', '', 9)
            pdf.set_text_color(90, 90, 90)
            for line in metadata_lines:
                pdf.multi_cell(content_width, 5, _pdf_safe_text(line))
            pdf.set_text_color(0, 0, 0)
            pdf.ln(3)
        except Exception as exc:
            logger.warning("Failed to render metadata: %s", exc)
            pdf.set_text_color(0, 0, 0)
            pdf.ln(3)

    for idx, block in enumerate(blocks):
        try:
            _render_block_to_pdf(pdf, block)
        except Exception as exc:
            logger.error("Failed to render block %d: %s", idx, exc)
            # Continue with next block instead of failing entire PDF

    logger.debug("Rendered %d content blocks for %s", len(blocks), file_path)

    pdf_output = pdf.output(dest='S')
    # fpdf returns bytearray, convert to bytes if needed
    pdf_bytes = bytes(pdf_output) if isinstance(pdf_output, bytearray) else pdf_output
    buffer = BytesIO(pdf_bytes)
    buffer.seek(0)
    return buffer


def generate_document_pdf(relative_path: str) -> Tuple[BytesIO, Path]:
    logger.info("Generating PDF for %s", relative_path)
    absolute_path = resolve_document_path(relative_path)
    if not absolute_path.exists() or not absolute_path.is_file():
        raise FileNotFoundError(f'File not found: {relative_path}')
    pdf_buffer = _build_pdf_buffer(absolute_path)
    logger.info("Successfully generated PDF for %s", absolute_path)
    return pdf_buffer, absolute_path


__all__ = [
    'list_document_groups',
    'resolve_document_path',
    'generate_document_pdf',
    'SUPPORTED_PDF_EXTENSIONS'
]
